name = "ValueHistories"
uuid = "98cad3c8-aec3-5f06-8e41-884608649ab7"
authors = ["JuliaML and contributors"]
version = "0.5.6"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
DataStructures = "0.17, 0.18, 0.19"
RecipesBase = "0.2.3, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
